name: Integracion a DockerHub

on:
  push:
    branches: ["main"]

jobs:
    build:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login a DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_TOKEN}}
            
            - name: Build de la Docker Image
              run: |
                  docker build -t pagina-prueba .
            
            - name: push Docker File to Docker Hub
              run: |
                  docker tag pagina-prueba ${{secrets.DOCKERHUB_USERNAME}}/pagina-prueba:latest
                  docker push ${{secrets.DOCKERHUB_TOKEN}}/pagina-prueba:latest